### ISSUE TITLE
Add endpoint for creating user 

### ISSUE THREAD

**Issue by bajiat** [apinf/emq_dashboard#1]
# User story
> As an integrator
> I need an API endpoint (REST) for creating users
> so that I can create new EMQ users who can publish messages to topics

# Context
EMQ currently provides an HTTP API with several endpoints:

![EMQ HTTP API](https://cloud.githubusercontent.com/assets/2122679/21385407/1960c170-c777-11e6-97a9-7fe08d5c6591.png)

The `/users` endpoint seems to provide a listing of admin users, but does not seem to allow for the creation of users.

# Task
Extend the existing `/users` endpoint, so that it allows users to be created. Avoid creating a new endpoint, if possible. Rather, rely on HTTP verb and request structure to create a new user.

**Comment by frenchbread** [comment]
Closing this one in favor of https://github.com/apinf/platform/issues/2005
