### ISSUE TITLE
Add endpoint for ACL definitions

### ISSUE THREAD

**Issue by bajiat** [apinf/emq_dashboard#2]
# User story
> As an integrator
> I need an API endpoint (REST) for creating ACL rules
> so that I can control who can publish/subscribe to topics from my third party codebase

# Context
EMQ currently provides an HTTP API with several endpoints:

![EMQ HTTP API](https://cloud.githubusercontent.com/assets/2122679/21385407/1960c170-c777-11e6-97a9-7fe08d5c6591.png)

There does not seem to be an endpoint related to **getting** or **creating** ACL rules.

# Task
Create a new, or find an existing, endpoint for defining ACL rules via the REST API.

**Comment by frenchbread** [comment]
Closing this one in favor of https://github.com/apinf/platform/issues/2005
